// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Repeat_Button.H>

class GUI {
public:
	GUI();
	Fl_Double_Window* uiw;
private:
	inline void cb_DBG_i(Fl_Button*, void*);
	static void cb_DBG(Fl_Button*, void*);
	inline void cb_SM2_i(Fl_Button*, void*);
	static void cb_SM2(Fl_Button*, void*);
	inline void cb_SM3_i(Fl_Button*, void*);
	static void cb_SM3(Fl_Button*, void*);
	inline void cb_NewButton_i(Fl_Return_Button*, void*);
	static void cb_NewButton(Fl_Return_Button*, void*);
	inline void cb_Left_i(Fl_Repeat_Button*, void*);
	static void cb_Left(Fl_Repeat_Button*, void*);
	inline void cb_Up_i(Fl_Repeat_Button*, void*);
	static void cb_Up(Fl_Repeat_Button*, void*);
	inline void cb_Down_i(Fl_Repeat_Button*, void*);
	static void cb_Down(Fl_Repeat_Button*, void*);
	inline void cb_Right_i(Fl_Repeat_Button*, void*);
	static void cb_Right(Fl_Repeat_Button*, void*);
	inline void cb_Ambient_i(Fl_Button*, void*);
	static void cb_Ambient(Fl_Button*, void*);
	inline void cb_AmbientDown_i(Fl_Button*, void*);
	static void cb_AmbientDown(Fl_Button*, void*);
	inline void cb_WhiteUp_i(Fl_Button*, void*);
	static void cb_WhiteUp(Fl_Button*, void*);
	inline void cb_WhiteDown_i(Fl_Button*, void*);
	static void cb_WhiteDown(Fl_Button*, void*);
public:
	void show();
	void DBG_cb();
	void SM2_cb();
	void SM3_cb();
	void NewButton_cb();
	void Left_cb();
	void Up_cb();
	void Down_cb();
	void Right_cb();
	void Ambient_cb();
	void AmbientDown_cb();
	void WhiteUp_cb();
	void WhiteDown_cb();
};
#endif
